env:
    browser: true
    es6: true
extends: 'eslint:recommended'
plugin: 'ember:recommended'
plugins: ember
rules:
    indent:
      - error
      - 2
    linebreak-style:
      - error
      - windows
    quotes:
      - error
      - single
    semi:
      - error
      - always
    no-console:
      - off
